# Generated by Django 4.0.4 on 2022-05-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuestrouser',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nuestrouser',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
