# Generated by Django 4.0.4 on 2022-05-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_rename_imagen_nuestrouser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuestrouser',
            old_name='avatar',
            new_name='imagen',
        ),
    ]
